### ISSUE TITLE
Attempted to load class "DotenvFactory" from namespace "Dotenv\Environment".

### ISSUE THREAD

**Issue by christiancannata** [mbo2olivier/mukadi-wordpress-bundle#4]
I've followed readme instructions but when I try to run my sf application it show me the error:

Attempted to load class "DotenvFactory" from namespace "Dotenv\Environment".
Did you forget a "use" statement for another namespace?

env('WP_DIR', 'wp') in public/wp-config.php (line 6)

**Comment by mbo2olivier** [comment]
Thanks for reporting! this is due to the new Illuminate packages relying upon dotenv version 3. This was fixed. Check the documentation to see the change in the public/wp-config.php file.

we just released a new version (1.2.0).
