### ISSUE TITLE
Compatibility with Symfony 5

### ISSUE THREAD

**Issue by zfmaster** [mbo2olivier/mukadi-wordpress-bundle#8]
Because Symfony 5 has not so much differences from version 4, it should be easy to update it to support latest version

**Comment by zfmaster** [comment]
Connected it to Symfony 5 for my project and did pull request https://github.com/mbo2olivier/mukadi-wordpress-bundle/pull/9

**Comment by mbo2olivier** [comment]
thank for your contribution, let me check it out

**Comment by zfmaster** [comment]
I think this issue could be closed now :)
